<a href="https://colab.research.google.com/github/Hyuna13/AI/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%88%98%EC%A7%91_%EC%8B%9C%EA%B0%81%ED%99%942.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 고흐가 그린 붓꽃은 어떤 종류일까?

## 05 학습하기 



## 5-1. K-최근접 이웃(K-Nearest Neighbor, K-NN) 알고리즘이란?
- 새로운 데이터가 들어왔을 때 특성공간내에 데이터간의 거리가 가까운 데이터를 찾아서 그것의 레이블의 값으로 분류하는 알고리즘 
- K : 새로 입력된 데이터를 기준으로 가장 거리가 가까운 데이터의 개수 

## 5-2. K-NN 알고리즘을 이용한 붓꽃 분류기 
```python
def 붓꽃분류기(분류하고 싶은 데이터, 분류된 데이터, K):
  1) 분류하고 싶은 데이터와 분류된 데이터 사이의 거리 계산하기
  2) 분류하고 싶은 데이터와 가까운 순서대로 나열하기
  3) 가장 가까운 K개 데이터 중에서 레이블별 빈도 세기 
  4) return K개 데이터 중 최다 빈도의 붓꽃 레이블값 반환하기
```


## 5-3. 프로그램 작성하기 


### [Step 1] 붓꽃 데이터를 불러와 출력하기
- https://www.kaggle.com/uciml/iris

In [1]:
# Iris.csv 파일 업로드하기 
from google.colab import files

uploaded = files.upload()

Saving Iris.csv to Iris.csv


In [2]:
# 데이터 불러오기
import pandas as pd

# (실습) 붖꽃 파일 불러와 iris 데이터프레임 만들기
iris = pd.read_csv('Iris.csv')    

# (실습) 처음부터 5개까지 데이터 출력하기
print(  iris.head(5)  )

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


### [Step 2] 150개 데이터의 특성 데이터와 종류 데이터를 나누어 저장하기 
- 붓꽃 특성 :features 저장
  - 꽃받침 길이 : SepalLengthCm (1번 인덱스)
  - 꽃받침 너비 : SepalWidthCm (2번 인덱스)
  - 꽃잎 길이 : PetalLengthCm (3번 인덱스)
  - 꽃잎 너비 : PetalWidthCm (4번 인덱스)

- 붓꽃 종류 : target_value 저장
  - 꽃 종류 : Species (5번 인덱스)
    - Iris 종류 : Iris-setosa, Iris-versicolor, Iris-virginica

In [3]:
# 150개 데이터의 특성 데이터(features)와 종류 데이터(target_value)를 나누어 저장하기
# (실습) numpy 불러오기
import numpy as np

# 계산의 편의를 위해 데이터셋의 형식을 numpy로 변환
# (실습) iris 데이터프레임을 넘파이 배열로 변경하기 
xy = np.array(iris)

# (실습) 배열의 1~4번 인덱스 데이터를 features 배열에 저장
features = xy[:, 1:5]
print(features)

# (실습) 배열의 마지막 인덱스의 데이터 target_value 배열에 저장
target_value = xy[:, -1]
print(target_value)

[[5.1 3.5 1.4 0.2]
 [4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.0 3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.0 1.4 0.1]
 [4.3 3.0 1.1 0.1]
 [5.8 4.0 1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.0 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.0 3.0 1.6 0.2]
 [5.0 3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.0 3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.0 1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.0 3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.0 3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.0 1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.0 3.3 1.4 0.2]
 [7.0 3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

###[Step 3] 유클리드 거리법을 이용하여 두 데이터간의 거리를 구하는 함수 선언하기
- 유클리디안 거리 계산함수 만들기 

   $ Distance(A, B) = \sqrt{(A - B)^2} $

   $ ex) A(x_1, y_1), B(x_2, y_2)$ <br>
   - $ Distance(A,B) = \sqrt{{(x_2 - x_1)^2} + {(y_2 - y_1)^2}}$

In [6]:
# (실습) Distance 함수 만들기
def Distance(A, B): 
    return np.sqrt(np.sum(np.power((A-B), 2)))

- [Tip] 유클리디안 거리 계산함수 예

In [7]:
import numpy as np

# 두 점 A(1, 2)와 B(5, 7) 선언
A = np.array([1, 2])
B = np.array([5, 7])

# 두 점 사이의 거리를 계산하여 변수 distance에 저장하기 
#distance = np.sqrt(np.sum(np.power((A-B), 2)))
distance = Distance(A, B)
print(distance)

# 변수 distance에 저장된 값을 소수점 셋째자리에서 반올림하기 
distance = round(distance, 2)

# 계산결과 출력하기 
print("두 점 A(1, 2)와 B(5, 7) 사이의 거리는 {0} 입니다.".format(distance))

6.4031242374328485
두 점 A(1, 2)와 B(5, 7) 사이의 거리는 6.4 입니다.


[Step 4] 붓꽃 분류 작성하기 



```python
def 붓꽃분류기(분류하고 싶은 데이터, 분류된 데이터, K):
  1) 분류하고 싶은 데이터와 분류된 데이터 사이의 거리 계산하기
  2) 분류하고 싶은 데이터와 가까운 순서대로 나열하기
  3) 가장 가까운 K개 데이터 중에서 레이블별 빈도 세기 
  4) return K개 데이터 중 최다 빈도의 붓꽃 레이블값 반환하기
```

  - Unknown : 분류하고 싶은 데이터
  - features : 분류된 데이터(붓꽃 특성 데이터)
  - target_value : 붓꽃 종류

#### **< 아이리스 붓꽃 분류기 만들기 >**   
**① 거리 구하기**
```
 distance = [4.16, ….0.27, ….0.3, …. 0.26]
 ```
**② 거리가 작은 순으로 인덱스 저장하기(index)**
```
  index = [149, 127, 139 … …. ]
```
**③ 거리가 가장 가까운 곳의 붓꽃 종류 추가**
  - target_value : 붓꽃 종류가 들어있는 배열 
  - result : target_result에 붓꽃 종류가 들어오면 각 인덱스 위치값을 하나씩 증가하기 (0번 : Iris-setosa, 1번 : Iris-versicolor, 2번 : Iris-virginica)
```
target_value[index[0]]  > Iris-virginica > result[2] +=1
target_value[index[1]] > Iris-virginica > result[2] +=1
target_value[index[2]] > Iris-virginica > result[2] +=1
```


In [11]:
# 붓꽃 분류기 함수 K_NN(기준이 될 데이터, 붓꽃 특성 데이터, K) 작성하기
# Unknown(분류하고 싶은 데이터), features(분류된 데이터, 붓꽃 특성 데이터), K(가장 가까운 데이터 갯수)

def K_NN(Unknown,features,K):
    # ①_데이터간의 거리 계산
    # distance_result(유클리디안 거리 계산 결과 저장할 데이터)
    distance_result = np.zeros(150) 
    for i in  range(150):
      # (실습) 유클리디안 거리 구해서 저장하기
        distance_result[i]= Distance(Unknown, features[i])
    print("distance_result : ",distance_result)

    # ②_분류하려는 데이터와 가까운 순서대로 나열 : 작은값부터 순서대로 데이터의 인덱스 반환해줌(0 : 가장 작은 값) 
    # (실습) 계산된 거리값이 증가하는 순으로 인덱스가 정렬됨 : index(거리가 가장 작은 값 순으로 인덱스를 저장한 배열)
    index = distance_result.argsort()
    print("index = ", index)   # 가장 작은 값의 인덱스가 149임 
    
    # ③_K개 데이터의 레이블(붓꽃)을 저장할 target_result 선언 
    # target_result : 거리가 가장 가까운 곳의 붓꽃 종류를 추가하는 배열 
    # result(target_result에 붓꽃 종류가 들어오면 각 인덱스위치값을 하나씩 증가하기) - (예) setosa이면 0번 인덱스 1씩 증가
    target_result = []
    result=[0,0,0]   # 0번 : Iris-setosa, 1번 : Iris-versicolor, 2번 : Iris-virginica
    # K = 3이면 i : 0~2
    for i in range(K):
      # index[0] : 거리가 가장 가까운 곳의 인덱스 반환 / target_result(거리가 가장 가까운 곳의 붓꽃 종류 추가)
      # (실습)거리가 가장 가까운 곳의 붓꽃 종류 추가
        target_result.append(    target_value[index[i]]     )
        if target_result[i]=='Iris-setosa':
           result[0]+=1
        elif target_result[i]=='Iris-versicolor':
             result[1]+=1
        else:
             result[2]+=1
    print("target_result", target_result)
    # ④_레이블의 빈도가 가장 높은 값 반환
    # (실습) result에 있는 값중 가장 큰 값의 인덱스를 max_result에 저장함 
    max_label=result.index(max(result))
    species = {0:"setosa", 1:"versicolor", 2:"virginica"}
    species_result = species[max_label]
    return species_result

###[Step 5] 붓꽃 분류 함수를 사용하여 가상의 데이터 분류하기 
- Iris.csv 파일의 150개 붓꽃 데이터 중 마지막 150번째 데이터와 150번째 데이터와 유사한 가상의 데이터를 만들어서 분류결과 확인하기 
```
<test_1>
Id	SepalLengthCm	SepalWidthCm	PetalLengthCm	PetalWidthCm	Species
149	     6.2	         3.4	         5.4	         2.3	    Iris-virginica
<test_2>
SepalLengthCm    SepalWidthCm    PetalLengthCm    PetalWidthCm
6                     2.9             5                2
```



In [12]:
# (실습) 마지막 150번째 데이터(features 인덱스 번호 : 149)
test_1 = features[149]

# (실습) 150번째와 유사한 가상의 데이터 
test_2 = np.array([6, 2.9, 5, 2])

# (실습) K_NN 분류 함수를 이용하여 분류하기(K=5)
result_1 = K_NN(test_1, features, 5)
result_2 = K_NN(test_2, features, 5)

# 결과 출력
print("실제 데이터를 분류한 결과 : {}".format(result_1))
print("가상 데이터를 분류한 결과 : {}".format(result_2))

distance_result :  [4.14004831 4.15331193 4.29883705 4.14969878 4.17372735 3.81837662
 4.21781934 4.0607881  4.30232495 4.10609303 4.03236903 4.02243707
 4.21781934 4.63141447 4.33358974 4.11339276 4.17851648 4.1024383
 3.80657326 4.0607881  3.81182371 4.00624512 4.62817459 3.73898382
 3.76430604 3.95221457 3.89615195 4.03236903 4.11096096 4.03608721
 4.00374824 3.91535439 4.18927201 4.22492603 4.10609303 4.3150898
 4.17252921 4.10609303 4.38748219 4.03980198 4.21307489 4.37492857
 4.39203825 3.84057287 3.67151195 4.14125585 4.01123422 4.24028301
 4.04598566 4.14125585 1.25299641 0.86023253 1.06770783 1.4525839
 0.86023253 0.83066239 0.67082039 2.28910463 1.         1.47648231
 2.23830293 0.9486833  1.58113883 0.60827625 1.61245155 1.14017543
 0.73484692 1.3190906  1.08627805 1.50665192 0.36055513 1.24096736
 0.73484692 0.77459667 1.07238053 1.06770783 1.04880885 0.81240384
 0.68556546 1.84390889 1.64316767 1.76635217 1.37840488 0.37416574
 0.83666003 0.75498344 0.9486833  1.17898261 1

###[Step 6] 고흐가 그린 붓꽃 그림의 데이터 분류하기 
- 고흐 붓꽃 그림의 실제 크기 : 가로 93cm, 세로 71cm

\begin{array}{c|c|c|c}
\text{Id}&\text{SepalLength}&\text{SepalWidth}&\text{PetalLength}&\text{PetalWidth}\\\hline
1&2.7&2.4&1.65&0.67\\
2&5.84&5.48&3&2.16\\
3&3.97&4.01&1.7&0.67
\end{array}


In [13]:
# 그림에서 수집한 데이터
ID_1 = np.array([2.7, 2.4, 1.65, 0.67])
ID_2 = np.array([5.84, 5.48, 3, 2.16])
ID_3 = np.array([3.97, 4.01, 1.7, 0.67])


# (실습) K_NN 분류기 함수를 이용하여 분류하기
result_1= K_NN(ID_1, features, 3)
result_2= K_NN(ID_2, features, 3)
result_3= K_NN(ID_3, features, 3)

# 분류 결과 출력하기
print(result_1,result_2,result_3)

distance_result :  [2.69321369 2.34166607 2.23235302 2.08408253 2.64828246 3.10087085
 2.19303443 2.55605164 1.85024323 2.38272953 3.0370051  2.37347846
 2.27099097 1.88345427 3.54871808 3.61875669 3.12016025 2.67757353
 3.3315762  2.8070269  2.91777312 2.74688915 2.38608466 2.56931898
 2.38608466 2.42350985 2.52297444 2.77549995 2.74470399 2.20531177
 2.26349288 2.89575551 3.08016233 3.37096425 2.38272953 2.52059517
 3.06486541 2.38272953 1.89562655 2.64639377 2.59988461 1.87333926
 1.96809553 2.5509606  2.80274865 2.22921511 2.8184038  2.12917825
 2.94845722 2.52653913 5.38195132 4.8105509  5.42046123 3.71071422
 4.89810167 4.20468786 4.89258623 2.76972923 4.95574414 3.45476483
 2.9968984  4.2179853  4.06957    4.65246171 3.58600056 4.95836667
 4.19301801 3.97635511 4.59362602 3.69694468 4.69887221 4.19992857
 4.92152415 4.61556064 4.62162309 4.86470965 5.23692658 5.35195291
 4.466699   3.54561701 3.55631832 3.48588583 3.87858222 4.87313041
 4.05726509 4.56917936 5.14600816 4.5748661